services:
  - type: web
    name: playwright-render
    env: node
    buildCommand: |
      npm install
      npx playwright install
    startCommand: node download-report.js
    envVars:
      - key: NODE_ENV
        value: production
