services:
  - type: web
    name: playwright-report-runner
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install --with-deps
    startCommand: node download-report.js
    envVars:
      - key: NODE_ENV
        value: production
